version: "3"

services:
  facilita-juridico-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=facilta
      - POSTGRESQL_PASSWORD=facilta
      - POSTGRESQL_DATABASE=facilta
  facilita-juridico-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=facilta@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=facilta
